# Generated by Django 5.1.15 on 2026-08-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_dietarypreference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='analytics_opt_out',
            field=models.BooleanField(default=False),
        ),
    ]
