# Generated by Django 5.1.15 on 2026-08-27 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_block'),
        ('pins', '0007_sharedlist_expires_at_sharedlist_kind_sharedlistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('harassment', 'Harassment or bullying'), ('spam', 'Spam'), ('inappropriate', 'Inappropriate content'), ('impersonation', 'Impersonation'), ('other', 'Other')], max_length=20)),
                ('detail', models.TextField(blank=True, max_length=1000)),
                ('reported_comment', models.TextField(blank=True)),
                ('reported_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='pending', max_length=12)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pins.pin')),
                ('reported_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_report',
                'ordering': ['status', 'created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='accounts_report_queue_idx')],
            },
        ),
    ]
