# Generated by Django 5.1.15 on 2026-08-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': [models.OrderBy(models.F('resolved_at'), nulls_first=True), 'created_at']},
        ),
    ]
