# Generated by Django 5.1.15 on 2026-08-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_pin_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
