# Generated by Django 5.1.15 on 2026-08-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_default_pin_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified_insider',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
