# Generated by Django 5.1.15 on 2026-09-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_is_verified_insider'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='digest_hour',
            field=models.PositiveSmallIntegerField(default=19),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_daily_digest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_friend_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_friend_request',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
