# Generated by Django 5.1.15 on 2026-09-07 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_profile_digest_hour_profile_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='digest_hour',
            field=models.PositiveSmallIntegerField(default=19, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
