# Generated by Django 5.1.15 on 2026-09-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_profile_digest_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='digest_prompt_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='policy',
            field=models.CharField(choices=[('gdpr', 'GDPR'), ('pdpo', 'PDPO'), ('digest', 'Daily digest'), ('terms', 'Terms of service')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notify_daily_digest',
            field=models.BooleanField(default=False),
        ),
    ]
