# Generated by Django 5.1.15 on 2026-04-13 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('category', models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('side', 'Side')], default='main', max_length=10)),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'restaurants_menu_item',
                'ordering': ['category', 'name'],
            },
        ),
    ]
