# Generated by Django 5.1.15 on 2026-04-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
