# Generated by Django 5.1.15 on 2026-05-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_menuitem_image_url_alter_restaurant_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
