# Generated by Django 5.1.15 on 2026-08-15 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_drop_menuitem_boolean_flags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name', 'id']},
        ),
    ]
