# Generated by Django 5.1.15 on 2026-08-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_restaurant_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo_ref',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
