# Generated by Django 5.1.15 on 2026-08-19 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_photo_url_by_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='reservation_provider',
            field=models.CharField(blank=True, choices=[('opentable', 'OpenTable'), ('thefork', 'TheFork'), ('resy', 'Resy'), ('sevenrooms', 'SevenRooms'), ('quandoo', 'Quandoo'), ('tablecheck', 'TableCheck'), ('meitre', 'Meitre'), ('direct', "Restaurant's own site"), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reservation_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reservation_url',
            field=models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
