# Generated by Django 5.1.15 on 2026-08-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_restaurant_reservation_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='reservation_provider',
            field=models.CharField(blank=True, choices=[('opentable', 'OpenTable'), ('thefork', 'TheFork'), ('resy', 'Resy'), ('sevenrooms', 'SevenRooms'), ('quandoo', 'Quandoo'), ('tablecheck', 'TableCheck'), ('meitre', 'Meitre'), ('woki', 'Woki'), ('tock', 'Tock'), ('covermanager', 'CoverManager'), ('direct', "Restaurant's own site"), ('other', 'Other')], max_length=20),
        ),
    ]
