# Generated by Django 5.1.15 on 2026-08-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_alter_restaurant_reservation_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='kind',
            field=models.CharField(choices=[('dietary', 'Dietary'), ('general', 'General'), ('highlight', 'Highlight'), ('vibe', 'Vibe'), ('occasion', 'Occasion'), ('scene', 'Scene')], db_index=True, default='general', max_length=20),
        ),
    ]
