# Generated by Django 5.1.15 on 2026-08-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_seed_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
