# Generated by Django 5.1.15 on 2026-08-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_restaurant_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
