# Generated by Django 5.1.15 on 2026-09-07 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=10)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen_at',),
                'indexes': [models.Index(fields=['user', '-last_seen_at'], name='notificatio_user_id_edefeb_idx')],
            },
        ),
        migrations.CreateModel(
            name='DigestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_date', models.DateField()),
                ('item_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-local_date',),
                'constraints': [models.UniqueConstraint(fields=('user', 'local_date'), name='one_digest_per_user_per_day')],
            },
        ),
        migrations.CreateModel(
            name='NotificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('friendship_request', 'Friend request received'), ('friendship_accepted', 'Friend request accepted')], max_length=32)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('discarded', 'Discarded')], default='pending', max_length=12)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['state', 'created_at'], name='notificatio_state_99afdc_idx'), models.Index(fields=['state', 'locked_at'], name='notificatio_state_f337f4_idx')],
            },
        ),
    ]
