services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: muse_backend
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - muse_net

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: muse_nginx
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - muse_net

networks:
  muse_net:
    driver: bridge
