# Generated by Django 5.1.15 on 2026-08-19 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0016_photo_url_by_place_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('save_to_map', 'Saved to map'), ('venue_card_view', 'Venue card viewed'), ('venue_detail_view', 'Venue detail viewed'), ('external_action_click', 'External action clicked')], max_length=32)),
                ('destination', models.CharField(blank=True, choices=[('directions', 'Directions'), ('reservation', 'Reservation'), ('website', 'Website')], max_length=20)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='restaurants.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', '-created_at'], name='analytics_e_name_19adf9_idx'), models.Index(fields=['restaurant', 'name', '-created_at'], name='analytics_e_restaur_ef5c5b_idx')],
            },
        ),
    ]
