# Generated by Django 5.1.15 on 2026-08-19 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('restaurants', '0017_restaurant_reservation_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyVenueStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(blank=True, max_length=200)),
                ('month', models.DateField()),
                ('name', models.CharField(choices=[('save_to_map', 'Saved to map'), ('venue_card_view', 'Venue card viewed'), ('venue_detail_view', 'Venue detail viewed'), ('external_action_click', 'External action clicked')], max_length=32)),
                ('destination', models.CharField(blank=True, choices=[('directions', 'Directions'), ('reservation', 'Reservation'), ('website', 'Website')], max_length=20)),
                ('count', models.PositiveIntegerField(default=0)),
                ('deduped_count', models.PositiveIntegerField(default=0)),
                ('unique_users', models.PositiveIntegerField(default=0)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_stats', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'analytics_monthly_venue_stat',
                'ordering': ['-month', 'restaurant_name'],
                'indexes': [models.Index(fields=['-month', 'name'], name='analytics_m_month_a4849a_idx')],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'restaurant_name', 'month', 'name', 'destination'), name='unique_monthly_venue_stat')],
            },
        ),
    ]
