# Generated by Django 5.1.15 on 2026-08-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0005_delete_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='is_favourite',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
