# Generated by Django 5.1.15 on 2026-08-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0006_pin_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlist',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedlist',
            name='kind',
            field=models.CharField(choices=[('auto', 'Everything that matches a filter'), ('curated', 'A hand-picked shortlist')], default='auto', max_length=10),
        ),
        migrations.CreateModel(
            name='SharedListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=280)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pins.pin')),
                ('shared_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pins.sharedlist')),
            ],
            options={
                'db_table': 'pins_shared_list_item',
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('shared_list', 'pin'), name='unique_pin_per_shared_list')],
            },
        ),
    ]
