# Generated by Django 5.1.15 on 2026-08-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0007_sharedlist_expires_at_sharedlist_kind_sharedlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='visibility',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('friends', 'Friends only'), ('private', 'Private')], max_length=10, null=True),
        ),
    ]
