# Generated by Django 5.1.15 on 2026-09-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0008_pin_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlist',
            name='voting_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ShortlistVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_key', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='pins.sharedlistitem')),
            ],
            options={
                'db_table': 'pins_shortlist_vote',
                'indexes': [models.Index(fields=['item'], name='pins_shortl_item_id_92b1eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('item', 'voter_key'), name='unique_vote_per_item_and_voter')],
            },
        ),
    ]
