# Generated by Django 5.1.15 on 2026-08-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceDetailsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255)),
                ('field_mask', models.CharField(max_length=1000)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['fetched_at'], name='place_details_fetched_idx')],
                'constraints': [models.UniqueConstraint(fields=('place_id', 'field_mask'), name='uniq_place_details_cache_key')],
            },
        ),
    ]
