# Generated by Django 5.1.15 on 2026-08-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_ref', models.CharField(max_length=1000)),
                ('width', models.PositiveIntegerField()),
                ('file', models.ImageField(upload_to='place-photos/')),
                ('attribution', models.JSONField(blank=True, default=list)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['fetched_at'], name='place_photo_fetched_idx')],
                'constraints': [models.UniqueConstraint(fields=('photo_ref', 'width'), name='uniq_place_photo_key')],
            },
        ),
    ]
