# Generated by Django 5.1.15 on 2026-09-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_placephoto_by_place_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, unique=True)),
                ('is_healthy', models.BooleanField(default=True)),
                ('checked_at', models.DateTimeField()),
                ('changed_at', models.DateTimeField()),
                ('last_error', models.TextField(blank=True)),
                ('alerted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'integration health',
            },
        ),
    ]
