# Generated by Django 5.1.15 on 2026-09-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_integrationhealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationhealth',
            name='last_downtime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
