# Generated by Django 5.1.15 on 2026-09-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=16, unique=True)),
                ('min_supported', models.CharField(help_text='Below this version the app blocks with no way out. Semantic, e.g. 1.3.0', max_length=32)),
                ('latest', models.CharField(help_text='Newest published version. Between this and the minimum, the app suggests.', max_length=32)),
                ('store_url', models.URLField(blank=True, default='', help_text='Where the blocking screen sends people. Store link, or direct download.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'app version policy',
                'verbose_name_plural': 'app version policies',
            },
        ),
    ]
