# Generated by Django 5.1.15 on 2026-04-05 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('pinned', 'pinned'), ('rated', 'rated'), ('updated', 'updated'), ('joined', 'joined'), ('friendship', 'became friends with')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='pins.pin')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_targeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'db_table': 'feed_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='feed_activi_created_438983_idx'), models.Index(fields=['actor', '-created_at'], name='feed_activi_actor_i_77bdbd_idx')],
            },
        ),
    ]
